appName: icodervn

namespace: apps

userFrontend:
  name: user-frontend
  image: 
    name: k8s/user-frontend
    

imagePullSecrets:
  name: harbor-secret
dockerRegistry:
  name: hub.icoder.vn

tag: v1.7
