appName: icodervn

namespace: apps

userFrontend:
  name: user-frontend
  image: 
    name: k8s/user-frontend
    tag: v1.0.0

imagePullSecrets:
  name: harbor-secret
dockerRegistry:
  name: hub.icoder.vn

