apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5G" # Increase the proxy body size to 5GB
    cert-manager.io/cluster-issuer: http-01-production
spec:
  ingressClassName: nginx
  rules:
    - host: api.icoder.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-{{ .Values.apiGateway.name }}
                port:
                  number: 8080
  tls:
    - hosts:
        - api.icoder.vn
      secretName: api-icoder-vn