apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.apiGateway.name }}
    tier: api-gateway
