apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.apiGateway.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
      tier: api-gateway
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
        tier: api-gateway
    spec:
      containers:
      - name: api-gateway-container
        image: {{ .Values.dockerRegistry.name }}/{{ .Values.apiGateway.image.name }}:{{ .Values.tag }}
        ports:
        - containerPort: 80
        env:
        {{- range .Values.apiGateway.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
