apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.authServer.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: http-01-production
spec:
  ingressClassName: nginx
  rules:
    - host: accounts.icoder.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-{{ .Values.authServer.name }}
                port:
                  number: 8080
  tls:
    - hosts:
        - accounts.icoder.vn
      secretName: accounts-icoder-vn
