apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.userService.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.userService.name }}
    tier: api-user-service
