apiVersion: v1
kind: Service
metadata:
  name: "service-{{ .Values.user-frontend.name }}"
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.user-frontend.name }}
    tier: user-frontend