apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.user-frontend.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: http-01-production
spec:
  ingressClassName: nginx
  rules:
    - host: icoder.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-{{ .Values.user-frontend.name }}
                port:
                  number: 80
  tls:
    - hosts:
        - icoder.vn
      secretName: icoder-vn