apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.user-frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.user-frontend.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.user-frontend.name }}
      tier: user-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.user-frontend.name }}
        tier: user-frontend
    spec:
      containers:
      - name: user-frontend-container
        image: "{{ .Values.docker-registry.name }}/{{ .Values.user-frontend.image.name }}:{{ .Values.user-frontend.image.tag }}"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
